services:
  - type: web
    name: scriptkiddie
    env: docker
    repo: https://github.com/Dimitar871/ScriptKiddie
    branch: ScriptKiddie
    rootDir: .
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:sTlz9u0ji7uLxgs6L0jlow13CgcA/QrIgJy2DNtb+hI=
      - key: APP_NAME
        value: Laravel
      - key: APP_URL
        value: https://scriptkiddie.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1eatfje5dus73b7cke0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: scriptkiddie_db
      - key: DB_USERNAME
        value: scriptkiddie_db_user
      - key: DB_PASSWORD
        value: eOjyqQKtELbbOd9HTHYip2PAQXEf7g0U
      - key: SESSION_DRIVER
        value: database
